### ISSUE TITLE
Problems with Serve

### ISSUE THREAD

**Issue by Ley212** [x0b/rcloneExplorer#25] opened 2019-10-14 12:01 UTC
Still some problems with Serve it starts but after starting webdav can browse for 10 seconds then get connection lost.
No info on error logs.

The older versions before 1.9 no problems

**Comment by x0b** [comment] 2019-10-14 13:31
No info in the logs means that rclone did not detect any error and exited normally. 

We'll need some information
- Did you allow remote access, set a username or a password?
- What application(s) are you using to access the WebDAV server?
- Which is the last version where it properly worked?

There is really not much of a difference between 1.8.x and 1.9.x for the serving functionality - this might be a bug in rclone itself (which was updated from 1.49.3 in 1.8.2 to 1.4.5 in 1.9.2)

**Comment by Ley212** [comment] 2019-10-14 14:41
I try both with remote access username and without doesn't matter.
I try with Mixplorer and Solid Exlorer i always use them without problems.
Version 1.7.4 from Kaczmarkiewicz still works fine with Serve.

Think your version from 1.7.5 till 1.8.2 was without problems. 
Will test 1.8.2 for to be sure let you know.

When i mount Webdav with your version i can browse 2 folders then it stop without error. I must restart Serve and can browse again 2 folders and stop. In the browser when i go to 127.0.0:8080 its the same.

Maybe it's something with the latest Rclone version hat gives the problems.

**Comment by Ley212** [comment] 2019-10-14 14:49
Have downloaded version 1.8.2 and that works fine. So maybe something with Rclone version wrong.

**Comment by Ley212** [comment] 2019-10-14 14:54
Oopps it's working now!! I had uninstalled version 1.8.2 and installed 1.9.1 and now it keeps working. Before i had override the old version and not uninstalled first. So this topic can be closed.

**Comment by x0b** [comment] 2019-10-14 15:06
That's great. I was just preparing a test build of with the old rclone version, so if it turns out that there are still issues in serve, just reopen and i'll upload that test version.

**Comment by Ley212** [comment] 2019-10-14 15:26
I will, but it's working great now!

**Comment by Ley212** [comment] 2019-10-14 16:32
Just wanted to let you know problem is back again, very strange thing.
It stops working after browsing 2 or 3 maps. 

When i start up Kaczmarkiewicz version it keeps working all the time.

I see 1 difference between your version and from Kaczmarkiewicz version. 
By Kaczmarkiewicz version i get the message in Brave when i have started webdav 127.0.0.1:8080 method not Allowed.

In your version it shows the complete directory structure when i have Serve running in webdav.
After 2, 3 maps browsing the file browsers Solid Explorer and MiXplorer stop showing and the Browser (Brave) answer: This page has not send any information 
ERR_EMPTY_RESPONSE (In some way it lose connection)

**Comment by x0b** [comment] 2019-10-15 08:18
Okay, I've prepared two test builds that you can [download here](https://drive.google.com/drive/folders/1B4mmjf3eKYQZASDKNcM9z69QC0V4B33j?usp=sharing).
 - one with the old rclone version (1.49.3)
 - one with the new rclone version (1.49.5)

Also, both these builds have more aggressive logging and will log a lot more. This should help a lot towards actually figuring out what is happening here.

To test them:
  1. Export your rclone config
  2. Uninstall the currently installed version
  3. Install a debug version
  4. Import your rclone config
  5. Go to Settings > Logging and enable "Use logs".
  6. Try to reproduce the issue
  7. Get the log file from ```Android/data/ca.pkay.rcloneexplorer.x0b/files/logs/log.txt``` on your SD card or internal storage and send it to  x0bdev@gmail.com (it may contain filenames so you shouldn't post it here)

**Comment by Ley212** [comment] 2019-10-15 11:24
Hi, thanks for help but cannot do anything at the the moment. My phone got bricked yesterday Moto G5 seems my internal memory just died. So use old phone now will find a better one soon. Will download the files and let you know when i have a good phone again.


You may close this topic if you want, will contact you by email when i know  more.

**Comment by x0b** [comment] 2019-10-15 14:37
That sucks. I'll leave the issue open.

**Comment by Ley212** [comment] 2019-10-18 16:18
Hi, i have done some tests (view hours) with rclone on a older Acer Zest Android 6.0 without problems Serve keeps on running now! I could not reproduce the connection lost.
Later i have test it on a Samsung phone with Android 9 and Serve keeps running there to. This was  tested both with debug1.9.1-rclone1.49.5.apk en the latest published version 1.9.1 both works good. 
So maybe there was more wrong with my old Moto G5 before it totally crashed. 
Nice to have a good updated Android rclone browser with Serve running again!!

**Comment by x0b** [comment] 2019-10-19 17:15
Okay, that sounds great. I'll close this now.

**Closed by x0b** 2019-10-19 17:15 UTC
Labels: bug
